Eng 7708/fpjs latency
Neuro-ID/neuroid-ios-sdk pull request #182
Opened 2024-04-25 15:04 UTC by cometman

2024-05-07 16:31 UTC, quacke-nid submitted a review, later dismissed

2024-05-08 21:57 UTC, kishisaka-nid commented
Possible to get the wifi/cell connection type in a ct element like the javascript SDK is doing? Android is filling this with either "cell" or "wifi" strings depending on the connection type. I don't think android can get the RTT(round trip time) or effective type. If not no problem I think. They really require the latency. 

  l: latency,
  ct: getConnectionType(),
  rtt: getRTT(),
  et: getEffectiveType(),

2024-05-08 22:55 UTC, cometman commented
@kishisaka-nid added connectionType to NIDEvent string

2024-05-09 18:28 UTC, kishisaka-nid approved these changes

2024-05-10 00:31 UTC, kishisaka-nid approved these changes

2024-05-10 02:49 UTC, quacke-nid commented on NeuroID/NeuroIDClass/Extensions/NIDLog.swift
> +        contextString = "rid=\(mutableEvent.rid ?? "") c=\(mutableEvent.c ?? false) l=\(mutableEvent.l)"
Indentation

2024-05-10 02:56 UTC, quacke-nid commented on NeuroID/NeuroIDClass/Extensions/NIDAdvancedDevice.swift
> +               if advancedDeviceSignals {
indentation

2024-05-10 03:30 UTC, quacke-nid reviewed
LGTM! Just a few minor nits!

2024-05-10 13:52 UTC, kevinsites requested changes

2024-05-10 13:52 UTC, kevinsites commented on NeuroID/NeuroIDClass/Extensions/NIDAdvancedDevice.swift
> +        nidEvent.ct = NetworkMonitoringService.connectionTypeAccessor.rawValue
Note:
We have a variable on the NeuroID class `networkMonitor` that is an instance of the `NetworkMonitoringService` class, is there a reason we wouldn't use that with the `connectionType` attribute instead?

2024-05-10 13:52 UTC, kevinsites commented on NeuroID/Utilities/NetworkMonitoringService.swift
> +    internal static var connectionTypeAccessor: ConnectionType = .unknown
Similar to the above comment, why are we storing the same property twice when we create a class instance?

2024-05-10 13:52 UTC, kevinsites commented on SDKTest/NeuroIDClassTests.swift
> +        XCTAssertTrue(validEvent.count == 1)
NIT: Can we add spacing to separate the setup vs. test vs. assertion for readability?

2024-05-10 14:00 UTC, kevinsites approved these changes

2024-05-10 14:12 UTC, priya-xavier approved these changes

2024-05-10 14:33 UTC, merged