ENG-8301-update random id generated with nid prefix
Neuro-ID/neuroid-ios-sdk pull request #204
Opened 2024-07-16 22:48 UTC by priya-xavier

[ENG-8301](https://neuro-id.atlassian.net/browse/ENG-8301)

2024-07-16 23:07 UTC, priya-xavier commented
Adds `nid-`prefix to all generated ids including session id, client id, screen name etc. Eg. "NeuroID SessionId:", "nid-13392CE6-0F87-4AA2-98D2-77EC23F0A4C1"

2024-07-17 14:37 UTC, kevinsites requested changes

2024-07-17 14:37 UTC, kevinsites commented on SDKTest/NIDParamsCreatorTests.swift
> +        let expectedValue = 40
Can we update these tests to ensure we see that prefix?

2024-07-17 15:46 UTC, kevinsites approved these changes

2024-07-17 18:01 UTC, kishisaka-nid approved these changes

2024-07-17 18:30 UTC, merged